### ISSUE TITLE
Stop using our own button debounce function

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pysteamworks#2]
There's a function in `robotpy-wpilib-utilities` to do debouncing.

**Comment by auscompgeek** [comment]
I mentioned this to @ArthurAllshire a few days ago:

>```
> 16:20 <davo> I hear robotpy_ext already has a button debouncer https://robotpy.readthedocs.io/projects/utilities/en/latest/robotpy_ext.control.html#module-robotpy_ext.control.button_debouncer
> 16:59 <arthur> works differently to how we want to do it i think
> 16:59 <arthur> we just make sure that the button has been pressed and released
> ```
