### ISSUE TITLE
Change exposure on camera for driver to use

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pysteamworks#21]
We only need to be targeting the peg when we are near it, which means the driver can see the robot.
When we are at the other end of the field we should change the exposure to a normal level so that the driver can use it to navigate.

**Comment by auscompgeek** [comment]
Does this mean we've decided against having a third camera for driving?

**Comment by james-ward** [comment]
What would be the advantage of a third camera?
We'd also need a USB hub to do that.

**Comment by auscompgeek** [comment]
Those were my thoughts too. I'm still not sure why the team decided to have a third camera in the first place.
